### ISSUE TITLE
Image size in the Blog Section

### ISSUE THREAD

**Issue by Tholkappiar** [ezpie1/ezpie#19]
**Describe the bug**
The Images in the blog section are not in the same size 

**To Reproduce**
_visit :_ https://ezpie.vercel.app/blogs

**Expected behavior**
The images size should be same for more readability of the page !

**Screenshots**

![Screenshot (90)](https://github.com/ezpie1/ezpie/assets/114584730/63435ff8-0d00-4c24-9ba7-123e01d7213d)

_PS :_   **I'm eager to work on this. Please assign this issue to me.**

**Comment by EzpieCo** [comment]
Sure why not @Tholkappiar you can work on this
