### ISSUE TITLE
Hacktoberfest blog for making an e commerce site

### ISSUE THREAD

**Issue by EzpieCo** [ezpie1/ezpie#3]
**This issue is for hacktoberfest.**

Topic: **Making a basic e commerce website**

Follow these steps to get started:

- [ ] Fork and clone the repository
- [ ] Follow the [contributor guide](https://github.com/ezpie1/ezpie/blob/master/CONTRIBUTING.md) to setup dev environment and creating a new blog
- [ ] Make a PR with an explaination:
  - An image of the blog
  - What all is explained it in
  - Any images used in the blog, show them as well

And that's all for your first contribution at epzie!

**Comment by yashthipsay** [comment]
Hi @EzpieCo, thank you for the opportunity!
I would like to work on making an e-commerce website blog for Hacktoberfest 2023!

**Comment by EzpieCo** [comment]
Hi @yashthipsay, yeah sure you can totally work in this issue for hacktoberfest! All you have to do is follow our contributors guide and you will be done!

Just one small request, do give us a star to fulfill our hearts please
