### ISSUE TITLE
Hacktoberfest blog for making a snake game using pygame

### ISSUE THREAD

**Issue by EzpieCo** [ezpie1/ezpie#4]
**This issue is for hacktoberfest.**

Topic: **Making a basic snake game using pygame**

Follow these steps to get started:

- [ ] Fork and clone the repository
- [ ] Follow the [contributor guide](https://github.com/ezpie1/ezpie/blob/master/CONTRIBUTING.md) to setup dev environment and creating a new blog
- [ ] Make a PR with an explaination:
  - An image of the blog
  - What all is explained it in
  - Any images used in the blog, show them as well

And that's all for your first contribution at epzie!

**Comment by Tholkappiar** [comment]
Hello Maintainers , I am interested in this issue ! could you assign this to me !

**Comment by EzpieCo** [comment]
Hi @Tholkappiar, yeah sure you can do this! hacktoberfest is after all made just for contributors like you. Just make sure you have gone through the contributors guide as it has everything explained. In case of any problem you can always pop over here and ask it.

Happy hacking!

**Comment by Tholkappiar** [comment]
```
[vite] Error when evaluating SSR module /src/supabase.ts:
|- Error: supabaseUrl is required.
```

**and** 

```
supabaseUrl is required.
  File:
    C:\Users\Thols\Desktop\Sample\ezpie\node_modules\@supabase\supabase-js\dist\main\SupabaseClient.js:56:19
  Code:
    55 |         if (!supabaseUrl)
    > 56 |             throw new Error('supabaseUrl is required.');
         |                   ^
      57 |         if (!supabaseKey)
      58 |             throw new Error('supabaseKey is required.');
      59 |         const _supabaseUrl = (0, helpers_1.stripTrailingSlash)(supabaseUrl);

```
- **Got this error while run the server in localhost , any idea on this !**

**Comment by Tholkappiar** [comment]
Hey ! Any Updates !?
