### ISSUE TITLE
Making the blog posts arranged in same size , in the blog section .

### ISSUE THREAD

**Issue by Tholkappiar** [ezpie1/ezpie#6]
**Is your feature request related to a problem? Please describe.**
An Enhancement on the Blog section for more comfortable UI experience !

**Expected behavior**
The blog posts should Arranged in the same size .

**Describe the solution you'd like**
Give div sizes

**To Reproduce**
Visit the URL : https://ezpie.vercel.app/blogs

**Additional context**

![ezpie](https://github.com/ezpie1/ezpie/assets/114584730/489adc10-4024-4e03-b477-5916e7664235)

**Comment by EzpieCo** [comment]
Hi @Tholkappiar, thanks for informing us about it, this isn't that new to us we have this thing laying around in our todo list, but haven't found an effective solution to it yet. We are still working on this issue and will get an effective answer soon, till then have to stay with what we have.
