### ISSUE TITLE
Fix all the blog links with fix height

### ISSUE THREAD

**Issue by EzpieCo** [ezpie1/ezpie#9]
## The Problem
The Blogs page has all the blogs, but the problem is with their height, each individual blog is having a different height.

## Expected Behaviour
All the divs should have a fix height

## Solution
Set a fix height for all the divs.

## Images
![image](https://github.com/ezpie1/ezpie/assets/104765117/9f72f383-75ab-46f0-86bd-d1df7a0a4542)

**Comment by hemanth110702** [comment]
Can I work on this issue?

**Comment by vd89** [comment]
hey, @EzpieCo  

Will like to work on the task, can you assign to me

**Comment by EzpieCo** [comment]
So sorry @vd89 and @hemanth110702.  @VivekChatterjee, had already done a fix for it. But you guys can stay around till I come up with some other issues for you to work on.

Give us a star so that you can stay updated about new simple to do issues for you to solve. Till then please wait for some issues to come up.

**Comment by EzpieCo** [comment]
Hi @vd89 and @hemanth110702, your in luck, we have two issues that are still in process, but since we haven't recived any information from the 2 people working on each of those, you can pick any one and comment so that I will assign that issue to you.
